import "./globals.css";
import NavBar from "@/components/Navbar/navbar";
import Footer from "@/components/Footer/footer";

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="body">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
